# More info on config here: https://github.com/golangci/golangci-lint#config-file
run:
  deadline: 10s
  issues-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  skip-dirs:
    - bin
    - vendor
    - tests

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2


linters:
  disable-all: true
  enable:
    - unused
    - deadcode
    - stylecheck
    - gosimple
    - govet
    - errcheck
    - deadcode
    - structcheck
    - varcheck
    - ineffassign
    - typecheck
    - dupl
    - goconst
    - goimports
    - megacheck
    - gosec
    - gocritic
    - staticcheck

issues:
  exclude-use-default: false
  exclude:
    - ST1003
    - ST1000
