# More info on config here: https://github.com/golangci/golangci-lint#config-file
version: "2"

run:
  timeout: 10s
  tests: true

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      colors: true

linters:
  default: none
  enable:
    - unused
    - govet
    - errcheck
    - ineffassign
    - dupl
    - goconst
    - gosec
    - gocritic
    - staticcheck
  settings:
    govet:
      enable:
        - shadow
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2

formatters:
  enable:
    - goimports

issues:
  exclude-use-default: false
  exclude:
    - ST1003
    - ST1000
